name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.repository != 'wippyai/template-module' }}
    uses: wippyai/template-module/.github/workflows/reusable-release.yml@v1
    with:
      publish: false
    secrets: inherit
